# -*- coding: utf-8 -*-
"""
═══════════════════════════════════════════════════════════════════════════
  POROSIM WEB — PORTADA CENTRAL E INSPECTOR DEL PROYECTO
═══════════════════════════════════════════════════════════════════════════
"""
import os
import pathlib
import streamlit as st

st.set_page_config(
    page_title="PoroSim — Home",
    layout="wide",
    initial_sidebar_state="expanded"
)

AQUI = pathlib.Path(__file__).resolve().parent
DIR_MALLAS = AQUI / "RESULTS" / "meshes"
DIR_SOLS   = AQUI / "RESULTS" / "solutions"
DIR_EQ     = AQUI / "RESULTS" / "equilibria"

st.title("🔬 POROSIM · PNP Scientific Computing Suite")
st.subheader("Hub and status for the Nanopore Electrochemical Simulation project")
st.divider()

# Métricas de estado en tiempo real
mallas_json = sorted(DIR_MALLAS.glob("**/*_limits.json")) if DIR_MALLAS.exists() else []
sols_h5     = sorted(DIR_SOLS.glob("**/Solutions_*.h5")) if DIR_SOLS.exists() else []
eq_h5       = sorted(DIR_EQ.glob("*.h5")) if DIR_EQ.exists() else []

c1, c2, c3 = st.columns(3)
c1.metric("📐 Computational Meshes", f"{len(mallas_json)}", help=f"Stored in RESULTS/meshes/")
c2.metric("⚡ PNP Solutions", f"{len(sols_h5)}", help=f"Stored in RESULTS/solutions/")
c3.metric("💾 Equilibrium Checkpoints", f"{len(eq_h5)}", help=f"V=0 solutions in RESULTS/equilibria/")

st.divider()

st.markdown("### 🏛️ Three-Pillar Architecture")

col_p1, col_p2, col_p3 = st.columns(3, gap="large")

with col_p1:
    with st.container(border=True):
        st.markdown("#### 📐 1. Mesher")
        st.caption("Geometry Pillar (Gmsh)")
        st.write("Generates the 2D axisymmetric channel geometry (cylindrical, conical or bullet), surface-charge zones (rings), charged films and reservoirs.")
        st.write("• Exports: `.xdmf`, `.msh` and `_limits.json`.")
        if mallas_json:
            st.success(f"Last mesh: `{mallas_json[-1].parent.name}`")
        else:
            st.info("No meshes generated yet.")
        st.page_link("1_mesher/gui_app.py", label="**Go to Mesher**", icon="➡️", use_container_width=True)

with col_p2:
    with st.container(border=True):
        st.markdown("#### ⚡ 2. PNP Solver")
        st.caption("Physics Pillar (FEniCS / MUMPS)")
        st.write("Solves the strongly coupled Poisson-Nernst-Planck system on the mesh in three stages: V=0 equilibrium, charge ramp and adaptive voltage sweep.")
        st.write("• Exports: `Solutions_*.h5`, `IV_curve_*.txt` and `_sim.json`.")
        if sols_h5:
            st.success(f"Last solution: `{sols_h5[-1].stem}`")
        else:
            st.info("No PNP solutions yet.")
        st.page_link("2_solver/gui_app.py", label="**Go to PNP Solver**", icon="➡️", use_container_width=True)

with col_p3:
    with st.container(border=True):
        st.markdown("#### 📊 3. Extractor")
        st.caption("Scientific and Plotting Pillar")
        st.write("Analyzes the solutions generated by the solver. Lets you explore I-V curves, rectification factor, differential conductance and 2D/1D spatial maps per voltage.")
        st.write("• Exports: publication-ready plots and `.csv`/`.xlsx` tables.")
        st.write("") # Espaciador para igualar alturas
        st.page_link("3_extractor/gui_extractor_app.py", label="**Go to Extractor**", icon="➡️", use_container_width=True)

st.divider()

st.markdown("### 🚀 Quick Navigation Guide")
st.info("👈 **Use the Streamlit navigation menu in the top-left sidebar** to open the interface of any Pillar directly (`1. Mesher`, `2. PNP Solver` or `3. Extractor`).\n\n"
        "Since it is natively connected, **any change in the pillars' code takes effect immediately** when you navigate to its page.")

with st.expander("📂 System Directories and Paths"):
    st.code(f"PoroSim Zenodo root  : {AQUI}\n"
            f"Meshes folder        : {DIR_MALLAS}\n"
            f"Solutions folder     : {DIR_SOLS}\n"
            f"Equilibria folder    : {DIR_EQ}", language="text")
